### PR TITLE
Update ru_RU.lang

### PR DESCRIPTION
**Pull request by labpaw**
The first step in greatly improved ru_RU.lang. Still a lot of todo. Also, is that intentional that uranium, iridium, titanium, rutile, steel textures are just completely black?

### CODE REVIEW

**Comment by buttilda** [comment]
The colours are calculated at runtime. They depend on what colours the ingots of the respective material are. Which means it can change depending on what resource pack you're using or what mods you are using.

If you don't like the AOBD calculated colour you can change it in the config file.

**Comment by labpaw** [comment]
Uranium and iridium for example don't have ingot variants. Maybe you can set them manually? Because, well, Uranium is somehow green and iridium is white (In IC2)

**Comment by buttilda** [comment]
Well AOBD wouldn't generate anything for them unless there's something in the Ore Dictionary registered as "ingotUranium" and "ingotIridium"

**Comment by labpaw** [comment]
Ok but still can you adjust colors for uranium and iridium? because... well, the black one is a _bit_ incorrect here :)

**Comment by buttilda** [comment]
AOBD doesn't have default colours =P
What if someone plays with a mod that has yellow uranium? Then the green dust would be incorrect.

Try deleting the config file and letting it regenerate (or at least the bit related to colours), or change the colours yourself.

**Comment by labpaw** [comment]
Ok. I'll try to.

**Pull request merged**
