### PR TITLE
Update ru_RU.lang, take 3 (Final)

### PR DESCRIPTION
**Pull request by labpaw**
The final part of translation :)

### CODE REVIEW

**Comment by buttilda** [comment]
That's what I call determination!

**Comment by labpaw** [comment]
Just look at [this](https://github.com/Glassmaker/ExtraTiC-Localization/blob/master/ru_RU.lang) and then to en_US.lang :D

**Comment by buttilda** [comment]
wow...
I don't know how you have the patience to do that XD

**Comment by TheVikingWarrior** [comment]
I don't know it either, i think he is some kind of machine

**Comment by labpaw** [comment]
Notepad++ helps a lot but it doesn't help in translating of Thaumcraft addon researches :) They just drives me crazy. Whole walls of text.

**Comment by TheVikingWarrior** [comment]
Yeah, i still have to update it since last december (+200 lines)

**Pull request merged**
