### PR TITLE
Mekanism v8 compatibility

### PR DESCRIPTION
**Pull request by unpairedbracket**
I think that this will add support for Mekanism 8 without breaking the existing support for Mekanism 7. I'll attempt to get all the necessary apis together to test it properly if you like, but I imagine you'll be able to do so a lot more quickly than I can.

### CODE REVIEW

**Comment by buttilda** [comment]
Looks like it will work. If it doesn't it probably only needs a few tweaks.
Thanks!

**Comment by buttilda** [comment]
Oh and if you ever want to build AOBD in the future, the easiest way to do it is to just delete the unwanted modules (and the respective enum values from CompatTypes) and then build. Downloading every single supported mod just for building would be way too cumbersome.

**Comment by kotoroshinoto** [comment]
how would one go about doing that @ganymedes01 ? would the resulting build still work as intended?

**Comment by buttilda** [comment]
-Download the source code
-Delete any unwanted modules from here: https://github.com/ganymedes01/Another-One-Bites-the-Dust/tree/mc1.7/src/main/java/ganymedes01/aobd/recipes/modules
-Delete the respective enum from here: https://github.com/ganymedes01/Another-One-Bites-the-Dust/blob/mc1.7/src/main/java/ganymedes01/aobd/lib/CompatType.java

Then build :3

Should work for pretty much every mod. A couple have some extra hooks spread around the place (Mekanism is one of them). So if after doing the steps above you still can't build, just find where the error is happening and delete those lines. Everything in the mod is very independent from the rest, so you can delete almost any part of it without causing issues.

**Comment by labpaw** [comment]
Would be better if you build it for me :smile:  I tried it but where I should drop mod sources(or mods itself)?

**Comment by kotoroshinoto** [comment]
will the mod still work WITH those other mods in the event that one does that?

**Comment by buttilda** [comment]
@Adaptivity I can give you a build tomorrow if you want. But if you want to build it yourself, after you download the src code, create a folder called "libs" inside the AOBD main folder and drop the mods in there that AOBD needs to build.

@kotoroshinoto It will run without crashing with those mods, but it won't add any recipes for them.

**Comment by kotoroshinoto** [comment]
Would that be the mods in source form?

**Comment by buttilda** [comment]
Nope. Compiled versions (same ones you'd play with).

**Comment by kotoroshinoto** [comment]
TY, i'll get to doing that at some point so I can keep up with progress

**Comment by buttilda** [comment]
Well, be careful! I often commit unfinished or untested code. So don't go running this on servers or anything you don't mind losing XD

If I implement a feature that you need released sooner then just let me know and I'll speed up the pace for an official release :3

**Comment by labpaw** [comment]
I'm need the build only for localization testing. Also, if I add all supported mods in my test pack, will I see all blocks/items in NEI search? If not, is it possible to force them all on? I need this only for testing of course.

**Comment by kotoroshinoto** [comment]
SimpleOreGrinder.java   Just some refactoring   a month ago

is there a version of this mod for 1.7.10? I've been looking but can't seem to find it

**Pull request merged**
